### ISSUE TITLE
Pinch and zoom - boundaries 

### ISSUE THREAD

**Issue by feluxz** [kmagiera/react-native-gesture-handler#587] opened 2019-04-26 18:00 UTC
Hello,
I'm trying to implement pinch to zoom features similar to the Scrollview zoom. I have started to modify the example code for "scaleAndRotate".

What i'm currently struggling with is: 
Have some kind of boundaries  for the scale, this can be achieved by the following code:
```
this._scale = this._pinchScale.interpolate({
      inputRange: [1, 5],
      outputRange: [1, 5 * 1.2],
      extrapolate: 'clamp',
    })
```
The problem with this is that the zoom is not preserved, it goes back to original scale.
 
The following example from the example code works but gives no boundaries, it zooms infinitely in both directions:
`this._scale = Animated.multiply(this._baseScale, this._pinchScale);`

So my question is, how can i combine these solutions or should i go another route? 

Thanks

**Comment by adamczyk777** [comment] 2019-04-30 07:16
Hi @feluxz. It seems like the issue is not related to gesture handler itself, more like some Animated stuff. To do complex interactions in react native I suggest you try https://github.com/kmagiera/react-native-reanimated if you are not already using it. There are some pinching examples in the demo. Closing the issue 🙂

**Closed by adamczyk777** 2019-04-30 07:16 UTC

**Comment by nuschris** [comment] 2019-06-27 08:50
Here my solution @feluxz :
this._scale = Animated.multiply(this._baseScale, this._pinchScale).interpolate({
      inputRange: [1, 5],
      outputRange: [1, 5 * 1.2],
      extrapolate: 'clamp',
    });
