### ISSUE TITLE
Tried to register two views with the same name GestureHandleRootView

### ISSUE THREAD

**Issue by tomderudderetna** [kmagiera/react-native-gesture-handler#457] opened 2019-02-07 06:59 UTC
After add a 2nd view in `createStackNavigator` i have always this error
`Ttried to register two views with the same name GestureHandleRootView`

**Comment by AlexisChup** [comment] 2019-02-07 14:17
I have the same error and I don't find the answer. Furthermore it is the same context, i follow a tuto and after install react-navigation and react-gesture-handler, and try to use a stack navigator, i have this screen on my emulator. Does someone knows why ?
Thanks

**Comment by vinhtq** [comment] 2019-02-11 03:37
Yes I have the same issue. Look like this library conflicts with react-navigation.

**Comment by zoharIOS** [comment] 2019-02-11 14:11
I got the same problem and after a research I found my problem:
I initialised a project with Expo blank template and answered no for the question "Yarn v1.9.4 found. Use Yarn to install dependencies?", later on I installed react-navigation with npm and reached the same problem: "Tried to register two views with the same name RNGestureHandlerButton"
(I believe it is the same one)

How to fix ?
I started the project again using yarn, and install the react-navigation with yarn.
> expo init MyProject
hit few times enter, when asked you can type a name for the application, answer "Y" to the following question
>Yarn v1.9.4 found. Use Yarn to install dependencies? (Y/n) Y
install react-navigation:
>cd MyProject
>yarn add react-navigation

start the app for simple "hello word" :
> yarn start

**Comment by vinhtq** [comment] 2019-02-12 02:15
I do not think the issue regarding setting up the project. As going through the document, react-navigation also use gesture handler library in their core. So that this will make the conflict

**Comment by Demky** [comment] 2019-03-19 10:04
hello, i have the same probllem.

Someone found a fix ?

**Comment by osdnk** [comment] 2019-03-19 17:15
Should be fixed with https://github.com/react-navigation/react-navigation-native/commit/c7cf4f67697ed7f1102002f55369a42cae495099

**Closed by osdnk** 2019-03-19 17:15 UTC

**Comment by guycode** [comment] 2019-03-27 00:23
no its not fixed

**Comment by snjoetw** [comment] 2019-04-28 13:46
Try this: https://stackoverflow.com/questions/54486525/tried-to-register-two-views-with-the-same-name-rngesturehandlerbutton

**Comment by osdnk** [comment] 2019-04-28 14:56
It’s not a bug in lib. It means that you have two instances of RNGH in deps. Check your yarn.lock

**Comment by AzadKshitij** [comment] 2020-09-24 18:24
just make sure that you have react-navigation/stack to be at the top of all your dependency and it will fix the issue... (at least for me)

**Comment by alexandre-eliot** [comment] 2022-01-08 13:50
I had the same error when importing { TouchableOpacity } from 'react-native-gesture-handler'
I figured I used { TouchableOpacity  } elsewhere in my app, which I was importing directly from 'react-native'
Importing the component only choosing one or the other, fixed it for me

**Comment by GustantoC** [comment] 2022-03-04 10:29
> just make sure that you have react-navigation/stack to be at the top of all your dependency and it will fix the issue... (at least for me)

I'm sorry i'm a bit new could you explain what do you mean by this? because all I have in my package is `react-navigation-stack` not `react-navigation/stack`. (Do you mean the import when we want to use the dependency or the one in package.json?)

And also, CMIIW, Doesn't the order of dependencies in package.json doesn't matter?

Thankyou
