### ISSUE TITLE
Require cycle: node_modules/react-native-gesture-handler/index.js

### ISSUE THREAD

**Issue by zhaokera** [kmagiera/react-native-gesture-handler#397] opened 2018-12-29 03:01 UTC
Project initiation
![simulator screen shot - iphone x - 2018-12-29 at 10 58 33](https://user-images.githubusercontent.com/10410744/50532743-d29c5880-0b58-11e9-9522-8e3c60b489db.png)  
"react": "16.6.3",
"react-native": "0.57.8",
"react-native-gesture-handler": "^1.0.12",
"react-navigation": "^3.0.9",

**Comment by piyushdesuvit** [comment] 2018-12-29 07:13
Having same issue

**Comment by DeVoresyah** [comment] 2018-12-29 20:54
same here, but there's no error like this in few days ago

**Comment by tphuc012** [comment] 2019-01-02 03:12
Having same issue at to day @@

**Comment by DeVoresyah** [comment] 2019-01-02 06:18
I check back to the react-navigation documentation and try what they're said

adding those to `MainActivity.java`
`package com.reactnavigation.example;

import com.facebook.react.ReactActivity;
+ import com.facebook.react.ReactActivityDelegate;
+ import com.facebook.react.ReactRootView;
+ import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {

  @Override
  protected String getMainComponentName() {
    return "Example";
  }

+  @Override
+  protected ReactActivityDelegate createReactActivityDelegate() {
+    return new ReactActivityDelegate(this, getMainComponentName()) {
+      @Override
+      protected ReactRootView createRootView() {
+       return new RNGestureHandlerEnabledRootView(MainActivity.this);
+      }
+    };
+  }
}`

**Comment by sunnylqm** [comment] 2019-01-03 14:01
This is caused by metro https://github.com/facebook/metro/issues/287

**Comment by osdnk** [comment] 2019-01-04 09:57
Fixed by https://github.com/kmagiera/react-native-gesture-handler/pull/391/files

**Closed by osdnk** 2019-01-04 09:57 UTC

**Comment by atkit** [comment] 2019-01-10 11:19
still, this:
```
import {
  PanGestureHandler,
  TapGestureHandler,
  State,
} from 'react-native-gesture-handler';
```
could be changed to this:
```
import {
  PanGestureHandler,
  TapGestureHandler,
  State,
} from './GestureHandler';
```
to avoid possibility of require cycle (it fixes warning btw)

**Comment by atkit** [comment] 2019-01-10 11:20
> Fixed by https://github.com/kmagiera/react-native-gesture-handler/pull/391/files

when new version will be released ?

**Comment by DeVoresyah** [comment] 2019-01-26 16:16
> Seems like it was released two days ago: https://github.com/kmagiera/react-native-gesture-handler/releases/tag/1.0.14

how to upgrade the package sir?

**Comment by kaloncheung124** [comment] 2019-01-26 18:10
If you're using npm, you should be able to run `npm install react-native-gesture-handler@latest --save`. This should also work for other packages. However, if this package is a dependency of another package, I think you have to wait for the devs of that other library to update their deoendencies first.

**Comment by rabingaire** [comment] 2019-02-04 08:56
Updating to 1.0.15 fixed my issue 👍

**Comment by BharathBunty** [comment] 2019-02-12 13:27
I've update to 1.0.15  still having same error

**Comment by divisble** [comment] 2019-04-25 05:54
Version 1.1.0 also has this error

**Comment by satyam90** [comment] 2020-05-20 13:29
Problem still exists with version 1.6.1 with iOS v13.4.1
