### ISSUE TITLE
Pinch gesture recognizer stops after 1-2 seconds on Android, hard to use on Android

### ISSUE THREAD

**Issue by brentvatne** [kmagiera/react-native-gesture-handler#26] opened 2017-09-13 18:31 UTC
See on Android it stops updating values in the middle of the gesture: https://www.youtube.com/watch?v=nIuLV8kPK8Q
See on iOS it works as expected, doesn't stop updating values: https://www.youtube.com/watch?v=CQZUJgWMphk

This is also easy to see inside of the example project -- on Android it's a lot harder to pinch to zoom than it is to rotate / pan, but on iOS it works as expected.

See on Android that pinch is tough to use: https://www.youtube.com/watch?v=gm7xXbNGTfk
See on iOS it is beautiful (with the exception of an error at the end, which of course just randomly happened while I was recording this): https://www.youtube.com/watch?v=g-LLvP5x6vk

**Comment by kmagiera** [comment] 2017-09-14 11:26
@brentvatne Like for the third video seems to be broken (https://www.youtube.com/watch?v=gm7xXbNGTfk)

**Comment by kmagiera** [comment] 2017-09-14 13:47
Can you reliably reproduce this issue? If yes on which phone?

As for the problem with how difficult it is to Pan vs Pinch there is one commit I landed just yesterday and didn't make it to alpha.21 which changes the default distance you need to pan before panhandler activates: 8f49f42b104da08782ee6048ae418ac06a60b39d

What I'd recommend doing is to play with `minDist` attribute of the Pan Responder. By default pinch activates when span changes by `ScaledTouchSlop` (which is an OS level constant https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res/values/config.xml#1964).

**Comment by kmagiera** [comment] 2017-09-14 13:50
I actually just realise I don't understand the issue. What do you mean by that it is harder to pinch than to rotate? If you have a single view on screen with only one pinch handler is it harder to use comparint to a single rotation handler register? Or maybe what you describe is related to the fact that there are other handlers that are more likely to "steal" gesture from pinch than they are to "steal" from rotation handler. Perhaps watching that video would help me

**Comment by brentvatne** [comment] 2017-09-14 14:04
Argh YouTube for some reason marked the video as a violation of their community guidelines (???) - I will share it with you over slack as I believe it makes it clear. Phone is nexus 5x

**Comment by brentvatne** [comment] 2017-09-14 14:07
actually here it is: http://url.brentvatne.ca/63zDN3

**Comment by brentvatne** [comment] 2017-09-14 21:19
resolved, thanks @kmagiera

**Closed** 2017-09-14 21:19 UTC
