### ISSUE TITLE
Unreliable Dragging & Pressing [android]

### ISSUE THREAD

**Issue by dk0r** [kmagiera/react-native-gesture-handler#15] opened 2017-08-30 16:57 UTC
I demo'd this lib via the included example app (`1.0.0-alpha.17`) on a physical Pixel XL (android@8.0.0):

**Issue**: Dragging and Pressing draggable-objects (aka pink boxes) is not reliable.

**Behavior**: The pink draggable boxes in the example app do not consistently respond to being single-tapped or dragged. Attempting to tap or drag a box requires multiple attempts (which often fail to be recognized) and is an overall frustrating experience. The non-native javascript `PanResponder` behaves significantly better (see **Note** below).

**Steps to Reproduce**:
1. Load the example app onto a physical device
2. Navigate to one of the following screens: `Draggable` **or** `Combo with RN's ScrollView`
3. Attempt to drag or single-press a pink draggable box
4. Notice that attempts to drag or tap these boxes fail more often than they succeed.

**Expected Behavior**: Dragging and tapping draggable-objects should be a fluid/seamless experience.

**Note**: If you navigate to the example app's `PanResponder` screen, you can see that **_the non-native javascript `PanResponder` is (for some unknown reason) more reliable/smooth than this libs native implementation_**.

**Comment by kmagiera** [comment] 2017-09-04 14:09
@dk0r thanks for trying it out and taking your time to report the issue!

Regarding the issues you might be experiencing in "Combo" screen I think those might be caused by the fact the draggable box has `minDist={100}` (see it here: [combo/index.js#L134](https://github.com/kmagiera/react-native-gesture-handler/blob/master/Example/combo/index.js#L134)). That I added there to test the scenario when one may not want the "pannable" view to get triggered when you scroll. So in order to activate it you need to drag your finger to the left or right (to avoid triggering scroll) as far as 100DP (android pixel independent units) to initiate the "pan".

As for the "PanResponder" or "Draggable" screens this property is not set and a default value for the minimal distance is being used (which is set to 10px at the moment: [PanGestureHandler.java#L11](https://github.com/kmagiera/react-native-gesture-handler/blob/master/android/lib/src/main/java/com/swmansion/gesturehandler/PanGestureHandler.java#L11)). I wonder if setting `minDist={0}` for you would fix the issue for you. Another idea that I have would be to use android "platform default" constant instead which can be retrieved from [ViewConfiguration#getScaledTouchSlop](https://developer.android.com/reference/android/view/ViewConfiguration.html#getScaledTouchSlop()) (at leats thats what android's ScrollView uses to determine when you move your finger far enough to start scrolling)

Anyhow: I'd appreciate if you get back and try the things I listed above, otherwise would very much like to see this issue recorded. If you have time of course I'd be glad if you could enable touch visualization on your test phone (instructions on [this youtube video](https://www.youtube.com/watch?v=yYPZTnmP3Ws)), then you can use this "adb" command to  start recording (stop with Ctr-C)
```
adb shell screenrecord --size 620x1080 /sdcard/demo.mp4
```

And to pull the recorded video from sdcard you can use the following command:
```
adb pull /sdcard/demo.mp4 demo.mp4
```

**Comment by kmagiera** [comment] 2017-09-26 08:12
@dk0r I hope my sugestions may help you with resolving the issue. I'm going to close it for now until you have time to provide some more input on your problem. Please feel free to reopen

**Closed by kmagiera** 2017-09-26 08:12 UTC
