### ISSUE TITLE
Swipeable not working on iPhone 5c

### ISSUE THREAD

**Issue by henrikra** [kmagiera/react-native-gesture-handler#131] opened 2018-03-13 09:26 UTC
When running examples on iPhone 5c (OS 10.3.3) they work very nicely! But `Gesture handler based SwipeableRow` has this weird effect when you are swiping them
I made video about the problem: [video](https://drive.google.com/file/d/1hWxbvR1OftXKMvj8bhP2u3CIOwhPUVyO/view?usp=sharing)

I have tested this on two different iPhone 5c phones and it reproduces on both.

Related #57 

Any ideas?

**Comment by henrikra** [comment] 2018-04-16 07:56
@kmagiera Any ideas for this?

**Comment by kmagiera** [comment] 2018-04-25 11:07
Hey @henrikra! Thanks for reporting. Do you know maybe if it is in fact related to 5C or more to the iOS version 10.3.3. Would be very helpful to eliminate one of these options.

**Comment by henrikra** [comment] 2018-04-25 11:13
Looks like it is because of iOS 10.3.3 because we have one user with iPhone 5s that have reported the same

**Comment by s0lus** [comment] 2018-04-26 17:11
Hey, @kmagiera! I have iPad mini 1 gen with iOS 9.3.5, and I have exactly the same issue as on the video. This issue can also be reproduced on iPhone 6 (iOS 9.3.5) and iPhone 5 (iOS 10.3.3). I think it's related to old iOS versions, and not to a particular device, because I don't have this issue on devices with iOS 11. And it's not reproducible on simulators.

**Comment by henrikra** [comment] 2018-05-16 11:00
@kmagiera Any idea for this?

**Comment by jarvisluong** [comment] 2018-05-30 12:11
This issue has been here for a quite long time but I'm still waiting for the fix :(

**Comment by pyankoff** [comment] 2018-07-03 16:09
Users reporting `Swipeable` not working on iOS 10.3.3
Any advice on where to dig? Thanks

**Comment by yellowspaceboots** [comment] 2018-08-23 03:38
I am having this same issue. Has anyone found a work around to get this working? Thanks!

**Comment by casperstr** [comment] 2018-09-18 10:30
Has anybody got this working yet?

**Comment by angly-cat** [comment] 2018-09-18 10:34
There's a workaround for this. Visual glitches are presented in places where there's no background. So, by manually setting a white or whatever `backgroundColor` for corresponding places (like screen container), one should be able to mitigate these glitches completely.

**Comment by osdnk** [comment] 2018-12-10 16:17
thanks @angly-cat for this workaround. We won't focus on this device, so this issue won't be fixed. Sorry 😢

**Closed by osdnk** 2018-12-10 16:17 UTC
Labels: bug

**Comment by VasilenkoVladislav** [comment] 2019-02-08 13:45
I had similar problem. I decided to check the model of the device.
if (deviceModel === 'iPhone 5' || deviceModel === 'iPhone 5c') {
    useNativeAnimations = false;
}
